in_progress_words = [
    "installing",
    "creating",
]
useful_status_words = [
    "copied",
    "copying",
    "creating",
    "installed",
    "installing",
    "patched",
    "patching",
    "processed",
    "processing",
]
choice_words = [
    "choice",
    "choose",
    "enter",
    "select",
]
choice_phrase = [
    "[a]ccept, [r]etry, [c]ancel",
    "[y]es or [n]o",
    "[y]es, [n]o, [c]ancel",
    "answer [y]es or [n]o.",
    "do you want",
    "enter a new",
    "is this correct?",
    "leave blank",
    "please enter",
    "please select",
    "would you like",
]
completed_with_warnings = [
    "installed with warnings",
]
failed_with_error = [
    "not installed due to errors",
    "installation aborted",
]
finished = [
    "process ended",
    "successfully installed      ",
]
eet_auto_fill = "Enter the full path to your BG:EE+SoD installation then press Enter."

[metadata]
mod_installer_version = "12.1.0"

[metadata.created]
secs_since_epoch = 1764506286
nanos_since_epoch = 473859137
